// IRC rooms are of the form #lang.wikipedia
// the list of languages is here:
// https://meta.wikimedia.org/wiki/List_of_Wikipedias#All_Wikipedias_ordered_by_number_of_articles
// https://meta.wikimedia.org/wiki/List_of_Wikipedias#1_000_000.2B_articles
var millionPlusLanguages = {
  en: true,
  ceb: true,
  sv: true,
  de: true,
  fr: true,
  nl: true,
  ru: true,
  es: true,
  it: true,
  pl: true,
  arz: true,
  ja: true,
  vi: true,
  war: true,
  zh: true,
  ar: true,
  uk: true,
  pt: true
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#100_000.2B_articles
var oneHundredThousandPlusLanguages = {
  fa: true,
  ca: true,
  sr: true,
  id: true,
  no: true,
  ko: true,
  fi: true,
  hu: true,
  cs: true,
  sh: true,
  ce: true,
  tr: true,
  'zh-min-nan': true,
  ro: true,
  eu: true,
  ms: true,
  tt: true,
  eo: true,
  he: true,
  hy: true,
  bg: true,
  da: true,
  azb: true,
  sk: true,
  kk: true,
  min: true,
  et: true,
  be: true,
  hr: true,
  lt: true,
  el: true,
  simple: true,
  az: true,
  gl: true,
  sl: true,
  ur: true,
  nn: true,
  ka: true,
  hi: true,
  th: true,
  ta: true,
  uz: true,
  la: true,
  cy: true,
  ast: true,
  vo: true,
  'zh-yue': true,
  mk: true,
  bn: true,
  lv: true,
  tg: true,
  my: true,
  af: true
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#10_000.2B_articles
var tenThousandPlusLanguages = {
  mg: true,
  bs: true,
  oc: true,
  sq: true,
  nds: true,
  mr: true,
  ky: true,
  'be-tarask': true,
  ml: true,
  te: true,
  new: true,
  br: true,
  vec: true,
  sw: true,
  pms: true,
  jv: true,
  pnb: true,
  ht: true,
  su: true,
  lb: true,
  ba: true,
  ga: true,
  szl: true,
  is: true,
  ku: true,
  lmo: true,
  cv: true,
  fy: true,
  tl: true,
  wuu: true,
  an: true,
  sco: true,
  diq: true,
  pa: true,
  ckb: true,
  yo: true,
  ne: true,
  bar: true,
  io: true,
  gu: true,
  als: true,
  kn: true,
  scn: true,
  bpy: true,
  ia: true,
  qu: true,
  mn: true,
  si: true,
  nv: true,
  'bat-smg': true,
  avk: true,
  xmf: true,
  or: true,
  gd: true,
  cdo: true,
  ilo: true,
  yi: true,
  am: true,
  bug: true,
  sd: true,
  nap: true,
  frr: true,
  os: true,
  hsb: true,
  'map-bms': true,
  mai: true,
  fo: true,
  li: true,
  sah: true,
  mzn: true,
  eml: true,
  ha: true,
  ace: true,
  crh: true,
  ps: true,
  gor: true,
  sa: true,
  bcl: true,
  wa: true,
  'zh-classical': true,
  lij: true,
  zu: true,
  mrj: true,
  mhr: true,
  hif: true,
  ban: true
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#1_000.2B_articles
var thousandPlusLanguages = {
  shn: true,
  as: true,
  hak: true,
  'roa-tara': true,
  hyw: true,
  pam: true,
  ie: true,
  nso: true,
  km: true,
  rue: true,
  se: true,
  bh: true,
  vls: true,
  'nds-nl': true,
  sn: true,
  mi: true,
  sc: true,
  nah: true,
  so: true,
  sat: true,
  vep: true,
  myv: true,
  gan: true,
  glk: true,
  kab: true,
  tk: true,
  co: true,
  bo: true,
  'fiu-vro': true,
  ab: true,
  mni: true,
  kv: true,
  csb: true,
  pcd: true,
  frp: true,
  udm: true,
  ug: true,
  gv: true,
  ay: true,
  kw: true,
  zea: true,
  ary: true,
  nrm: true,
  bjn: true,
  gn: true,
  mt: true,
  lez: true,
  lfn: true,
  stq: true,
  lo: true,
  mwl: true,
  skr: true,
  rm: true,
  olo: true,
  smn: true,
  lad: true,
  gom: true,
  fur: true,
  koi: true,
  ang: true,
  dsb: true,
  dty: true,
  ext: true,
  tyv: true,
  ln: true,
  'cbk-zam': true,
  dv: true,
  ksh: true,
  gag: true,
  bxr: true,
  pfl: true,
  pi: true,
  pag: true,
  av: true,
  awa: true,
  haw: true,
  ig: true,
  tay: true,
  rw: true,
  pap: true,
  xal: true,
  krc: true,
  szy: true,
  za: true,
  pdc: true,
  kaa: true,
  ak: true,
  inh: true,
  arc: true,
  to: true,
  kbp: true,
  jam: true,
  na: true,
  wo: true,
  tpi: true,
  kbd: true,
  atj: true,
  tcy: true,
  nov: true,
  ki: true,
  mdf: true,
  tet: true,
  lld: true,
  bi: true,
  lg: true,
  jbo: true,
  'roa-rup': true,
  lbe: true,
  kg: true,
  fj: true,
  ty: true,
  xh: true,
  srn: true,
  om: true,
  shi: true,
  nqo: true,
  trv: true,
  gcr: true,
  sm: true,
  ltg: true,
  alt: true
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#100.2B_articles
var hundredPlusLanguages = {
  nia: true,
  chr: true,
  tw: true,
  mnw: true,
  ks: true,
  pih: true,
  ny: true,
  got: true,
  cu: true,
  st: true,
  mad: true,
  kl: true,
  dag: true,
  tn: true,
  bm: true,
  ts: true,
  rmy: true,
  ve: true,
  chy: true,
  rn: true,
  tum: true,
  iu: true,
  ss: true,
  ch: true,
  pnt: true,
  ady: true,
  ik: true,
  ee: true,
  ff: true,
  din: true,
  sg: true,
  dz: true,
  ti: true,
  cr: true
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#10.2B_articles
var tenPlusLanguages = {
  
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#1.2B_articles
var onePlusLanguages = {
  ng: true,
  cho: true,
  kj: true,
  mh: true,
  ho: true,
  ii: true,
  aa: true,
  lrc: true,
  mus: true
};

// https://meta.wikimedia.org/wiki/List_of_Wikipedias#0_articles_in_language_(other_than_main_page)
var zeroLanguages = {
  hz: true,
  kr: true
};

var reallyLongTailWikipedias = [].concat(
    tenThousandPlusLanguages,
    thousandPlusLanguages,
    hundredPlusLanguages,
    tenPlusLanguages,
    onePlusLanguages,
    zeroLanguages);

var wikidata = {
  wikidata: true
};

var wikinews = {
    ja: true,
    zh: true,
    en: true,
    sr: true,
    pt: true,
    ko: true,
    ru: true,
    fr: true,
    ca: true,
    de: true,
    tr: true,
    es: true,
    it: true,
    ar: true,
    pl: true,
    no: true,
    uk: true,
    sv: true,
    bs: true,
    ro: true,
    eo: true,
    fa: true,
    sq: true,
    ta: true,
    el: true,
    bg: true,
    cs: true,
    fi: true,
    he: true,
    nl: true,
    sd: true,
    th: true,
    hu: true
};

module.exports = {
  millionPlusLanguages: millionPlusLanguages,
  oneHundredThousandPlusLanguages: oneHundredThousandPlusLanguages,
  reallyLongTailWikipedias: reallyLongTailWikipedias,
  wikidata: wikidata,
  wikinews: wikinews
};
